import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { GlobalProvider } from './providers/globalProvider';
import { TimersProvider } from './providers/timers';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'chefIT',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background min-h-screen md:grid md:justify-center`}
            >
                <div className='w-full h-full md:w-3xl'>
                    <GlobalProvider>
                        <TimersProvider>{children}</TimersProvider>
                    </GlobalProvider>
                </div>
            </body>
        </html>
    );
}
