import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { StepsProvider } from '@/app/providers/steps';
import { ModalContainer } from '@/shared/uikit/modal';
import { ModalStoreProvider } from '@/app/providers/modalProvider';
import { TimersProviderWrapper } from './providers/timers/index.wrapper';
import { SpeechRecognitionStoreProvider } from './providers/speechRecognitionProvider';
import { SpeechListener } from '@/features/speechListener';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'chefIT',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background min-h-screen flex justify-center`}
            >
                <div className='w-full min-h-screen md:w-3xl'>
                    <ModalStoreProvider>
                        <TimersProviderWrapper>
                            <StepsProvider>
                                <SpeechRecognitionStoreProvider>
                                    {/*<SpeechListener /> */}
                                    {children}
                                </SpeechRecognitionStoreProvider>
                                <ModalContainer />
                            </StepsProvider>
                        </TimersProviderWrapper>
                    </ModalStoreProvider>
                </div>
            </body>
        </html>
    );
}
